### ISSUE TITLE
Group 모니터링 설정 추가

### ISSUE THREAD

**Issue by ksiisk99** [GaJaMap/backend#404]
## Description
Group 모니터링 설정 추가

## To-do
- Group 모니터링 설정 추가

**Comment by Jang990** [comment]
타이머든 카운터든 게이지든 원하는 어노테이션 붙이고
http://localhost:9292/my-monitor/prometheus 들어가서 확인하면 추가돼있음
만약에 client.search로 어노테이션 등록하면
저 URL에 프로메테우스에는 client_search로 확인할 수 있음
중요한건 한 번은 요청이 들어와야지 저 URL에서 데이터를 사진처럼 확인할 수 있음
![image](https://github.com/GaJaMap/backend/assets/88225377/9509ebcc-f7f1-4bee-8b4d-acc3573593b8)

이게 확인되면 메트릭은 등록이 된거임
그러면 이제 그라파나 대시보드로 들어가서 add Panel로 만들면 됨

![image](https://github.com/GaJaMap/backend/assets/88225377/c70fbea4-421a-4198-a3a2-38fec73954e6)
내가 기존에 만든 쿼리는 이렇게 edit으로 들어가서 볼 수 있음

나 같은 경우는 그냥 쿼리랑 Legend만 설정하고 나왔음
쿼리는 VScode처럼 자동완성도 된다.
![image](https://github.com/GaJaMap/backend/assets/88225377/6275a99b-874b-4f5e-a26f-2b3514849d9d)

근데 처음말했듯 한 번은 요청이 들어와야지 메트릭을 확인할 수 있어서 
PR 병합해서 배포하고 요청을 한 번은 해야지 자동완성기능 사용가능할 듯

**Comment by ksiisk99** [comment]
ㅇㅋ 땡큐 로컬에 그라파나랑 프로메테우스 설치하고 한번 해볼게
